config/routes.rb
Rails.application.routes.draw do
  # get 'site/index'
  devise_for 'user'

  post 'add_comment' => 'site#add_comment'
  post 'set_isread' => 'comments#set_isread'
  get 'trello_oauth' => 'site#oauth_redirect'
  get 'trello_cb' => 'site#trello_cb'
  get 'trello_oauth_back' => 'trello_auths#update_oauth'
  get 'test' => 'site#test'
  get 'get_comments' => 'site#get_comments'
  root 'site#index'

  # :TODO: remove when production
  get 'all' => 'comments#all'
  get 'comments/all' => 'comments#all'
  resources :comments
  resources :trello_auths
end

app/models/comment.rb
include TextHelper

class Comment < ActiveRecord::Base
  belongs_to :user

  validates :trello_auth_id, presence: true
  validates :comment_id, presence: true


  # self.primary_keys = :trello_auth_id, :comment_id

  def self.get_isread mentioned_comments, trello_auth, current_username
    mentioned_comments.each do |comment|
      # add the isread field
      this_comment = self.where(trello_auth_id: trello_auth.id, comment_id: comment['id']).take
      if this_comment != nil
        comment['isread'] = true
      else
        comment['isread'] = false
      end
      comment['isreplied'] = false

      comment['data']['text'] = TextHelper.all comment['data']['text'], current_username
    end

    mentioned_comments
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    #@comments = Comment.all
    #Rails.logger.debug("current_user: #{current_user.inspect}\n")
    # @comments = current_user.trello_auth.comments
    @comments = current_user.trello_auth.comments
  end

  # GET /comments.all
  def all
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def set_isread
    puts 'set_isread'
    puts params
    puts
    value = params[:value] != 'true'
    comment_id = params[:comment_id]

    # check if trello+comment pair exists
    comment_exists = Comment.exists?(trello_auth_id: current_user.trello_auth.id, comment_id: comment_id)

    puts value, comment_id, comment_exists
    puts 'a0'
    if value and not comment_exists
      puts 'a'
      @comment = Comment.new(trello_auth_id: current_user.trello_auth.id, comment_id: comment_id)
      if @comment.save
        puts 'b'
        success = true
      end
    elsif not value and comment_exists
      puts 'c'
      @comment = Comment.where(trello_auth_id: current_user.trello_auth.id, comment_id: comment_id).take
      @comment.destroy
      success = true
    end

    respond_to do |format|
      if value
        if success
          format.html { redirect_to '/', notice: 'Comment marked as read.' }
          format.json { head :no_content }
        else
          format.html { redirect_to '/', notice: 'Unable to mark as read.' }
          format.json { render json: { :message => 'Unable to mark as read.' }, status: 400 }
        end
      else
        format.html { redirect_to '/', notice: 'Comment marked as unread.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:id, :is_read, :comment_id, :trello_auth_id, :user_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br>
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :comment_id %><br>
    <%= f.text_field :comment_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :trello_auth_id %><br>
    <%= f.number_field :trello_auth_id %>
  </div>
  <div class="field">
    <%= f.label :is_read %><br>
    <%= f.check_box :is_read %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/all.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>user_id</th>
      <th>trello_id</th>
      <th>comment_id</th>
      <th>is_read</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.id %></td>
        <td><%= comment.user_id %></td>
        <td><%= comment.trello_id %></td>
        <td><%= comment.comment_id %></td>
        <td><%= comment.is_read %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>user_id</th>
      <th>trello_auth_id</th>
      <th>comment_id</th>
      <th>is_read</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.id %></td>
        <td><%= comment.user_id %></td>
        <td><%= comment.trello_auth_id %></td>
        <td><%= comment.comment_id %></td>
        <td><%= comment.is_read %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @comment.id %>
</p>

<p>
  <strong>Is read:</strong>
  <%= @comment.is_read %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>