config/routes.rb
Rails.application.routes.draw do
  # get 'site/index'
  devise_for 'user'

  post 'add_comment' => 'site#add_comment'
  post 'set_isread' => 'comments#set_isread'
  get 'trello_oauth' => 'site#oauth_redirect'
  get 'trello_cb' => 'site#trello_cb'
  get 'trello_oauth_back' => 'trello_auths#update_oauth'
  get 'test' => 'site#test'
  get 'get_comments' => 'site#get_comments'
  root 'site#index'

  # :TODO: remove when production
  get 'all' => 'comments#all'
  get 'comments/all' => 'comments#all'
  resources :comments
  resources :trello_auths
end

app/controllers/site_controller.rb
require 'trello_lib'

class SiteController < ApplicationController
  before_action :authenticate_user!
  before_action :set_trello_auth, only: [:index, :add_comment, :get_comments]

  include TextHelper

  def set_trello_auth
    if not TrelloAuth.exists?(user_id: current_user.id)
      redirect_to trello_oauth_path
      return
    end

    token = current_user.trello_auth.access_token
    @t = TrelloLib.new token
  end

  def get_comments
    @me_trello = @t.get_user 'me'
    @trello_username = @me_trello['username']
    @me_avatar_url = @me_trello['avatarUrl']
    @trello_comments = Comment.get_isread @t.get_mentioned_comments, current_user.trello_auth, @trello_username

    avatar_urls = {}
    @trello_comments.each do |comment|
      # readable timestamp
      comment['formatDate'] = TextHelper.format_relative_time(comment['date'])

      # add avatar to the creator
      creator_id = comment['memberCreator']['id']
      if avatar_urls.has_key?(creator_id)
        comment['memberCreator']['avatarUrl'] = avatar_urls[creator_id]
      else
        avatar_url = @t.get_avatar_url creator_id, :size => :small
        comment['memberCreator']['avatarUrl'] = avatar_url
      end
    end
  end

  def index
    @me_trello = @t.get_user 'me'
  end

  def add_comment
    @ret = @t.add_comment params['card_id'], params['reply']
    respond_to do |format|
      if @ret
        format.html { redirect_to '/', notice: 'Replied.' }
        format.json { redirect_to '/get_comments' }
      else
        format.html { redirect_to '/', notice: 'Failed to reply the comment.' }
        format.json { render json: { :message => 'error' }, status: :unprocessable_entity }
      end
    end
  end

  def oauth_redirect
      redirect_to TrelloLib.step1_authorize_url
  end

  def trello_cb
    render layout: false
  end

  def test
    @trello_auth = current_user.trello_auth
    respond_to do |format|
      format.html { render :test, notice: 'Clicked test' }
      # format.json { render json: { :message => 'error' }, status: :unprocessable_entity }
      # format.json { render json: { :message => 'error' }, status: 400 }
      format.json { head :no_content }
    end
  end

  def test_reply
    @aa = params['hehe']
    @bb = params['commit']
  end
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/site/_avatar.html.erb
<div class="avatar-container">
  <% if member['avatarHash'] != nil %>
    <%= image_tag @t.get_avatar_url member['username'], :size => :small %><br />
  <% else %>
    <span><%= member['initials'] %></span><br />
  <% end %>
</div>

app/views/site/_form.html.erb
<%= form_tag("/add_comment", method: "POST", id: 'add_comment_form') do %>
  <%= label_tag :reply do %>
	  <%= render 'avatar', :member => me_trello %>
  <% end %>
  <%= hidden_field_tag :card_id, card_id %>
  <%= text_field_tag :reply, template_reply %>
  <%= button_tag '', type: 'submit', name: 'commit', value: 'Reply', class: 'btn btn-flat btn-default send-btn mdi-content-send' %>
<% end %>

app/views/site/add_comment.html.erb
<%= @pp.inspect %>

app/views/site/index.html.erb
<% content_for :navbar do %>
<div class="navbar navbar-default">
	<div class="container-fluid">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="/"><%= render 'avatar', :member => @me_trello %> <%= @me_trello['fullName'] || @me_trello['username'] %></a>
		  
		</div>
	
		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse navbar-responsive-collapse" id="navbar-collapse">
			<ul class="nav navbar-nav navbar-right">
				<li><%= link_to 'Switch Trello', trello_oauth_path %></li>
				<li><%= link_to 'Logout', destroy_user_session_path, :method => :delete %></li>
			</ul>
		</div><!-- /.navbar-collapse -->
	</div><!-- /.container-fluid -->
</div>
<% end %>
<% content_for :navbar do %>
  <%= javascript_include_tag 'comments', 'type' => 'text/jsx', 'data-turbolinks-track' => true %>
<% end %>

<div id="comment-container" class="col-xs-13 col-md-10 col-md-offset-1"></div>
<script type="text/jsx">
  React.render(
    <CommentList url="<%= get_comments_path %>" pollInterval={1200000} token="<%= form_authenticity_token %>" />,
    document.getElementById('comment-container')
  );
</script>

app/views/site/test.html.erb
<h2>Raised buttons</h2>
<button id="hehe" class="btn btn-default isread-btn"><i class="mdi-action-done"><span>&nbsp;</span></i></button>
<button id="hehe" class="btn btn-default isread-btn"><i class="mdi-action-done"><span>&nbsp;</span></i></button>
<br />
<a id="hehe" class="isread-btn btn btn-flat btn-default mdi-action-done"></a>
<a id="hehe" class="btn btn-flat btn-default mdi-content-send isread-btn"></a>
<br />
<button class="btn btn-default btn-raised">Colored</button>
<button class="btn btn-primary btn-raised">Colored</button>
<button class="btn btn-default btn-raised" disabled="">Disabled</button>
<button class="btn btn-default btn-raised btn-link">Noink</button>

app/views/site/trello_cb.html.erb
Loading...
<script>
window.location.href = '/trello_oauth_back?' + window.location.hash.substring(1);
</script>