config/routes.rb
Rails.application.routes.draw do
  # get 'site/index'
  devise_for 'user'

  post 'add_comment' => 'site#add_comment'
  post 'set_isread' => 'comments#set_isread'
  get 'trello_oauth' => 'site#oauth_redirect'
  get 'trello_cb' => 'site#trello_cb'
  get 'trello_oauth_back' => 'trello_auths#update_oauth'
  get 'test' => 'site#test'
  get 'get_comments' => 'site#get_comments'
  root 'site#index'

  # :TODO: remove when production
  get 'all' => 'comments#all'
  get 'comments/all' => 'comments#all'
  resources :comments
  resources :trello_auths
end

app/models/trello_auth.rb
class TrelloAuth < ActiveRecord::Base
  belongs_to :user
  has_many :comments

  validates :trello_id, presence: true
end

app/controllers/trello_auths_controller.rb
class TrelloAuthsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_trello_auth, only: [:show, :edit, :update, :destroy]

  # GET /trello_auths
  # GET /trello_auths.json
  def index
    #@trellos = Trello.all
    #@trellos = TrelloLib.new token
    @trello_auths = TrelloAuth.all
  end

  # GET /trello_auths/1
  # GET /trello_auths/1.json
  def show
  end

  # GET /trello_auths/new
  def new
    @trello_auth = TrelloAuth.new
  end

  # GET /trello_auths/1/edit
  def edit
  end

  # POST /trello_auths
  # POST /trello_auths.json
  def create
    @trello_auth = TrelloAuth.new(trello_params)

    respond_to do |format|
      if @trello_auth.save
        format.html { redirect_to @trello_auth, notice: 'Trello was successfully created.' }
        format.json { render :show, status: :created, location: @trello_auth }
      else
        format.html { render :new }
        format.json { render json: @trello_auth.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trello_auths/1
  # PATCH/PUT /trello_auths/1.json
  def update
    respond_to do |format|
      if @trello_auth.update(trello_auth_params)
        format.html { redirect_to @trello_auth, notice: 'Trello was successfully updated.' }
        format.json { render :show, status: :ok, location: @trello_auth }
      else
        format.html { render :edit }
        format.json { render json: @trello_auth.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_oauth
    # validate
    begin
      token = params['token']
      t = TrelloLib.new token
      me_trello = t.get_user 'me'
      trello_id = me_trello['id']
    #rescue Trello::Error
    rescue
      redirect_to '/', notice: 'Some problems occurred when updating oauth. 1'
      return
    end

    puts "update_oauth: #{params} #{token}"

    @trello_auth = current_user.trello_auth
    if @trello_auth
      @trello_auth.update(user_id: 0, access_token: '')
      if not @trello_auth.save
        redirect_to '/', notice: 'Some problems occurred when updating oauth. 2'
        return
      end
    end

    @trello_auth_token = TrelloAuth.where(trello_id: trello_id).take
    if @trello_auth_token
      if @trello_auth_token.user_id == 0
        @trello_auth_token.user_id = current_user.id
        @trello_auth_token.access_token = token
      else
        redirect_to '/', notice: 'Problem occurs when linking the Trello account.'
        return
      end
    else
      @trello_auth_token = TrelloAuth.new(user_id: current_user.id, trello_id: trello_id, access_token: token)
    end
    if not @trello_auth_token.save
      redirect_to '/', notice: 'Some problems occurred when updating oauth. 3'
      return
    end

    redirect_to '/', notice: 'TrelloAuth was successfully updated. 4'
    return
  end

  # DELETE /trello_auths/1
  # DELETE /trello_auths/1.json
  def destroy
    @trello_auth.destroy
    respond_to do |format|
      format.html { redirect_to trellos_url, notice: 'Trello was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trello_auth
      @trello_auth = TrelloAuth.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trello_auth_params
      params.require(:trello_auth).permit(:session_id, :user_id, :trello_id, :access_token)
    end
end

app/views/trello_auths/_form.html.erb
<%= form_for(@trello_auth) do |f| %>
  <% if @trello_auth.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trello_auth.errors.count, "error") %> prohibited this trello from being saved:</h2>

      <ul>
      <% @trello_auth.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :session_id %><br>
    <%= f.text_field :session_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :trello_id %><br>
    <%= f.text_field :trello_id %>
  </div>
  <div class="field">
    <%= f.label :access_token %><br>
    <%= f.text_field :access_token %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trello_auths/edit.html.erb
<h1>Editing TrelloAuth</h1>

<%= render 'form' %>

<%= link_to 'Show', @trello_auth %> |
<%= link_to 'Back', trello_auths_path %>

app/views/trello_auths/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing TrelloAuths</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Session</th>
      <th>User</th>
      <th>Trello</th>
      <th>Access token</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trello_auths.each do |trello_auth| %>
      <tr>
        <td><%= trello_auth.id %></td>
        <td><%= trello_auth.session_id %></td>
        <td><%= trello_auth.user_id %></td>
        <td><%= trello_auth.trello_id %></td>
        <td><%= trello_auth.access_token %></td>
        <td><%= link_to 'Show', trello_auth %></td>
        <td><%= link_to 'Edit', edit_trello_auth_path(trello_auth) %></td>
        <td><%= link_to 'Destroy', trello_auth, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trello', new_trello_auth_path %>

app/views/trello_auths/new.html.erb
<h1>New TrelloAuth</h1>

<%= render 'form' %>

<%= link_to 'Back', trello_auths_path %>

app/views/trello_auths/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Session:</strong>
  <%= @trello_auth.session_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @trello_auth.user_id %>
</p>

<p>
  <strong>Trello:</strong>
  <%= @trello_auth.trello_id %>
</p>

<p>
  <strong>Access token:</strong>
  <%= @trello_auth.access_token %>
</p>

<%= link_to 'Edit', edit_trello_auth_path(@trello_auth) %> |
<%= link_to 'Back', trello_auths_path %>